"""Tests for the constrained global fit.

The core assertions **synthesise spectra from the forward model** rather than reading
anything off disk, so they hold on a machine with no ``AMP_v1`` beside it and no
DataStore. Ground truth is then exactly known, which is the only way to test a fitter
without inheriting the very estimator being tested.

The answer-key tests at the bottom read real data and skip cleanly when it is absent.
They exist because a fitter that recovers its own forward model proves only that the
algebra round-trips — ``SUBAGENT_RULES`` §3.2 — and the corpus is what says whether the
branch is reached by anything real. **Order dependence is the case that made that
concrete**: the synthetic ladder cannot show it at all, because spectra
:func:`model_impedance` generated exactly give a cost surface with one reachable basin,
so the order-invariance test that discriminates is the one against the four NIST
standards, with the retired seeding restored in process as its control.
"""

from __future__ import annotations

import itertools
import math
from pathlib import Path

import numpy as np
import pytest

from softae.analysis.eis.calibration import CalibrationSet, FixtureConductance
from softae.analysis.eis.constrained_fit import (
    BEYOND_COVERAGE_POLICIES,
    BOUNDS,
    CONSENSUS_COST_FACTOR,
    CONSTRAINED_FIT_TOL,
    HOLDOUT_REFUSE_PCT,
    MIN_ARC_RESOLVED,
    ORDER_SPREAD_REFUSE_PCT,
    PARAM_NAMES,
    PER_SPECTRUM_PARAMS,
    QG_PLAUSIBLE_MAX,
    R_SOL_SEED_MULTIPLIERS,
    SHARED_PARAMS,
    SHARED_SEED_GRID,
    Admissibility,
    ConstrainedSpectrum,
    HoldoutReport,
    HoldoutResult,
    ImplausibleArtifact,
    InadmissibleFitSet,
    PoorGeneralisation,
    SharedArtifact,
    ShuntTable,
    UnmeasuredFixtureShunt,
    UnstableFitSurface,
    arc_is_resolved,
    check_admissible,
    conductance_r_sol,
    fit_frozen,
    fit_shared,
    fixture_admittance,
    holdout_report,
    implausible_shared,
    model_impedance,
    refuse_unless_generalises,
)

#: Arguments for the tests whose subject is something *other* than the multi-start —
#: tolerance handling, holdout bookkeeping, order invariance.
#:
#: The full grid costs ~25 s per :func:`fit_shared` on noise-free synthetic spectra and
#: minutes on the near-degenerate ones: four of its ten starts converge to a cost around
#: 1e-20 and then crawl there for thousands of iterations, which is a property of data
#: the forward model generated *exactly*, not of the optimiser — on the real corpus the
#: whole grid takes ~30 s. Paying the synthetic price in every test would put this file
#: at half an hour for no added coverage, so the two entries here stand in wherever the
#: grid's width is not the subject; the ``artifact`` fixture and the answer-key
#: in-sample test still run it at full width.
#:
#: The infinite limit is deliberate and explicit rather than incidental: two starts that
#: land in different basins leave one in consensus and a NaN spread, which
#: :func:`fit_shared` refuses on by design, and an explicit infinity is the only way to
#: ask for the artifact anyway.
FAST = dict(seed_grid=(SHARED_SEED_GRID[1], SHARED_SEED_GRID[3]),
            max_order_spread_pct=math.inf)

#: Three grid entries that all stop in the same shallow region of the surface at cost
#: ~0.6 and **disagree** about ``R_sol`` by ~6 % — measured, on the synthetic ladder.
#: Real multi-start disagreement, which is what the refusal is for.
POOR_STARTS = (SHARED_SEED_GRID[0], SHARED_SEED_GRID[2], SHARED_SEED_GRID[4])

# ── The forward model, and the truth the tests measure against ───────────────

#: One geometry, one interfacial chemistry — the three quantities the design shares.
TRUE_SHARED = {"Qg": 1.2e-9, "ng": 0.92, "nd": 0.76}

#: A conductivity ladder. The values bracket the NIST standards' fitted ``R_sol``.
TRUE_R_SOL = {"dilute_a": 70_000.0, "dilute_b": 38_000.0,
              "mid": 2_400.0, "concentrated": 800.0}

WIDE_BAND = (4.0, 2.0e5)


def synth(
    label: str,
    r_sol: float,
    *,
    band: tuple[float, float] = WIDE_BAND,
    n: int = 40,
    qd: float = 2e-6,
    pinned_l_H: float = 0.0,
    y_shunt: np.ndarray | None = None,
    shared: dict[str, float] | None = None,
) -> ConstrainedSpectrum:
    """A spectrum generated by :func:`model_impedance` itself, with known truth."""
    freq = np.logspace(math.log10(band[0]), math.log10(band[1]), n)
    params = dict(shared or TRUE_SHARED)
    params.update({"R0": 0.15 * r_sol, "R1": 0.85 * r_sol, "Qd": qd})
    ys = np.zeros(n, dtype=complex) if y_shunt is None else np.asarray(y_shunt)
    z = model_impedance(freq, params, ys, pinned_l_H)
    return ConstrainedSpectrum(label=label, freq_hz=freq, z=z, y_shunt=ys,
                               pinned_l_H=pinned_l_H, reference_ohm=r_sol)


@pytest.fixture(scope="module")
def ladder() -> list[ConstrainedSpectrum]:
    return [synth(label, r) for label, r in TRUE_R_SOL.items()]


@pytest.fixture(scope="module")
def artifact(ladder) -> SharedArtifact:
    """One good artifact, fitted once and shared by every test that only needs one.

    Module-scoped because :func:`fit_shared` now runs the whole seed grid and the
    spectra are frozen dataclasses over read-only arrays — there is nothing for a test
    to mutate, and refitting it a dozen times is the single largest cost in this file.
    """
    return fit_shared(ladder)


# ── The split: three shared, three per spectrum, L in neither ────────────────

def test_parameter_split_partitions_names_with_l_pinned_out() -> None:
    assert set(SHARED_PARAMS) | set(PER_SPECTRUM_PARAMS) == set(PARAM_NAMES)
    assert not set(SHARED_PARAMS) & set(PER_SPECTRUM_PARAMS)
    # L is pinned. A pinned quantity in the parameter vector is one bounds edit away
    # from being fitted, which is the defect overhaul F5 recorded.
    assert "L" not in PARAM_NAMES and "L" not in BOUNDS
    # Nor is a leak resistance, which would be degenerate against a supplied shunt.
    assert "Rleak" not in PARAM_NAMES


def test_fit_shared_recovers_the_shared_three_from_the_forward_model(artifact) -> None:
    for name, truth in TRUE_SHARED.items():
        assert getattr(artifact, name) == pytest.approx(truth, rel=1e-3), name
    # Canonical, not as-passed: the fit sorts the set before stacking so that the
    # residual vector is a function of the set (see fit_shared), and the labels record
    # the order actually fitted.
    assert artifact.labels == tuple(sorted(TRUE_R_SOL))
    assert artifact.railed() == ()


def test_fit_shared_shares_one_value_across_every_spectrum(ladder, artifact) -> None:
    """The property that distinguishes this from N independent fits."""
    assert set(artifact.shared) == set(SHARED_PARAMS)
    # Each spectrum's own truth differs in R_sol by ~90x, yet one triple serves all.
    for spec in ladder:
        fit = fit_frozen(spec, artifact)
        assert fit.R_sol == pytest.approx(spec.reference_ohm, rel=1e-3), spec.label


def test_fit_frozen_varies_only_the_per_spectrum_three(ladder, artifact) -> None:
    a = fit_frozen(ladder[0], artifact)
    b = fit_frozen(ladder[-1], artifact)
    # The per-spectrum parameters move with the spectrum...
    assert a.R0 != b.R0 and a.R1 != b.R1
    # ...while the artifact they were fitted against is unchanged by fitting, and a
    # refit of the same set lands in the same place.
    for name, value in fit_shared(ladder, **FAST).shared.items():
        assert value == pytest.approx(artifact.shared[name], rel=1e-6), name


# ── Order invariance — the defect this module was committed carrying ─────────
#
# `fit_shared` as committed at f79e463 built its starting point as a continuation:
# each spectrum seeded from the *previous* spectrum's fit, resetting only R0/R1, with
# the median of that chain as the stacked fit's x0. Reorder the input and the chain
# reorders, so the stacked fit starts somewhere else and `least_squares`, being local,
# finishes somewhere else. Measured on the four NIST standards: 24 permutations of the
# same four spectra spanned R_sol MAE 1.561 % to 1.065e9 %, with `check_admissible`
# True on all 24 and `railed()` firing on none.

def test_fit_shared_gives_one_answer_for_every_order_of_the_same_set(ladder) -> None:
    """All 24 permutations of one four-spectrum set, one artifact.

    **This assertion is not self-validating** and the file carries two things that say
    so: the control immediately below shows it goes red when order dependence is
    present, and ``test_answer_key_...order`` shows it goes red on the *real* corpus
    against the seeding this replaced. On noise-free synthetic spectra the retired
    continuation passes this test too — the cost surface has a single basin the model
    generated itself — which is exactly ``SUBAGENT_RULES`` §3.2 and the reason the
    answer-key version exists.
    """
    shared = [fit_shared(list(perm), **FAST).shared
              for perm in itertools.permutations(ladder)]
    assert len(shared) == 24
    for name in SHARED_PARAMS:
        values = [s[name] for s in shared]
        assert max(values) == pytest.approx(min(values), rel=1e-6), name


def test_the_order_invariance_check_goes_red_when_the_start_depends_on_order(
        ladder, monkeypatch) -> None:
    """Positive control — ``SUBAGENT_RULES`` §3.1(e).

    An invariance assertion is worth nothing unless order dependence, when it exists,
    reaches it. The start builder is replaced by one that seeds **every** spectrum from
    whichever spectrum happens to be first in the list — order-dependent by
    construction, in the same shape the continuation was — and the assertion above must
    then fail.
    """
    from softae.analysis.eis.constrained_fit import fit as module

    def first_spectrum_start(spectra, shared, tol):
        x0 = [shared[p] for p in SHARED_PARAMS]
        for _ in spectra:
            x0 += [module._seed(spectra[0])[p] for p in PER_SPECTRUM_PARAMS]
        return x0

    # Both halves of the fix come out: `_canonical_order` would otherwise make even a
    # deliberately order-dependent start builder order-free, and the control would come
    # back green while proving nothing — SUBAGENT_RULES §3.1's harness case.
    monkeypatch.setattr(module, "_canonical_order", lambda spectra: list(spectra))
    monkeypatch.setattr(module, "_stacked_start", first_spectrum_start)
    # Four orderings, not all 24: a bad start makes every descent slow, and four is
    # already enough to show the difference — measured, this construction spans 7.3 %
    # in Qg over the full 24 where the shipped one spans 0.
    orders = [ladder, ladder[::-1], [ladder[i] for i in (2, 0, 3, 1)],
              [ladder[i] for i in (1, 3, 0, 2)]]
    qg = [fit_shared(list(o), **FAST).Qg for o in orders]
    assert max(qg) > min(qg) * (1 + 1e-6), (
        "an order-dependent start produced the same Qg for every order, so the "
        "invariance test above cannot distinguish the two constructions")


def test_seed_grid_is_a_fixed_module_constant_not_derived_from_the_data() -> None:
    """The property that makes the fit order-free: nothing about the grid is fitted."""
    assert len(SHARED_SEED_GRID) >= 2
    for entry in SHARED_SEED_GRID:
        assert set(entry) == set(SHARED_PARAMS)
        for name, value in entry.items():
            lo, hi = BOUNDS[name]
            assert lo <= value <= hi, (name, value)
    # Decades either side of `_seed`'s default Qg, the same shape as
    # R_SOL_SEED_MULTIPLIERS one level down.
    qg = sorted({e["Qg"] for e in SHARED_SEED_GRID})
    assert qg[-1] / qg[0] >= 1e3
    assert len({e["nd"] for e in SHARED_SEED_GRID}) >= 2


def test_each_spectrums_start_depends_only_on_itself(ladder) -> None:
    """``_stacked_start`` is order-free by shape, and this reads that off directly.

    The per-spectrum block a spectrum gets must be the same block wherever it sits in
    the list — a stronger and far cheaper statement than the end-to-end permutation
    test, and the one that says *why* the end-to-end result holds.
    """
    from softae.analysis.eis.constrained_fit import fit as module

    entry = SHARED_SEED_GRID[0]
    forward = module._stacked_start(ladder, entry, CONSTRAINED_FIT_TOL)
    backward = module._stacked_start(list(reversed(ladder)), entry,
                                     CONSTRAINED_FIT_TOL)
    n_shared, n_each = len(SHARED_PARAMS), len(PER_SPECTRUM_PARAMS)
    for i in range(len(ladder)):
        j = len(ladder) - 1 - i
        assert forward[n_shared + i * n_each: n_shared + (i + 1) * n_each] == \
            pytest.approx(backward[n_shared + j * n_each: n_shared + (j + 1) * n_each])


# ── The order spread, and the refusal built on it ────────────────────────────

def test_fit_shared_reports_the_spread_between_its_starts(artifact) -> None:
    """:attr:`SharedArtifact.order_spread_pct`, the counterpart to seed_spread_pct."""
    assert artifact.n_starts == len(SHARED_SEED_GRID)
    assert 2 <= artifact.n_consensus <= artifact.n_starts
    assert artifact.order_spread_pct == pytest.approx(0.0, abs=1e-3)
    assert artifact.seed in SHARED_SEED_GRID
    assert f"{artifact.n_consensus}/{artifact.n_starts} starts" in artifact.describe()


def test_fit_shared_refuses_when_the_starts_do_not_agree(ladder) -> None:
    """Three starts that reach the same cost and different answers.

    :data:`POOR_STARTS` is not a contrivance in shape — they are entries of the shipped
    grid, and on this ladder all three stop at cost ~0.6 within a factor of 1.02 of each
    other, so all three are in consensus, and they disagree about ``R_sol`` by ~6 %. The
    threshold is then the only thing varied: above the measured spread the artifact is
    returned, below it the same fit refuses.
    """
    returned = fit_shared(ladder, seed_grid=POOR_STARTS)
    assert returned.n_consensus == len(POOR_STARTS)
    assert returned.order_spread_pct > 1.0

    with pytest.raises(UnstableFitSurface, match="order spread") as exc:
        fit_shared(ladder, seed_grid=POOR_STARTS, max_order_spread_pct=1.0)
    assert "not reproducible" in str(exc.value)


def test_fit_shared_refuses_when_only_one_start_reached_the_minimum(ladder) -> None:
    """A single descent cannot show that its minimum is reproducible.

    ``SUBAGENT_RULES`` §3.1(a): the spread is NaN there, and NaN must not be spelled the
    same way as "the starts agreed". One grid entry is the smallest instance of it.
    """
    with pytest.raises(UnstableFitSurface, match="1/1 consensus"):
        fit_shared(ladder, seed_grid=(SHARED_SEED_GRID[0],))


def test_unstable_fit_surface_is_recorded_as_a_refused_fold(ladder) -> None:
    """It subclasses InadmissibleFitSet so ``holdout_report`` records it, not crashes.

    The generalisation gate has to be lifted to *see* the record: with every fold
    refused there is nothing scored, the mean is NaN, and NaN refuses — which is the
    subject of its own test below.
    """
    assert issubclass(UnstableFitSurface, InadmissibleFitSet)
    report = holdout_report(ladder, kind="leave_one_out",
                            seed_grid=(SHARED_SEED_GRID[0],),
                            max_mean_abs_error_pct=math.inf)
    assert len(report.refused) == len(ladder)
    assert report.results == ()
    assert all("order spread" in reason for _, reason in report.refused)


def test_fit_shared_rejects_an_empty_seed_grid(ladder) -> None:
    with pytest.raises(ValueError, match="seed_grid is empty"):
        fit_shared(ladder, seed_grid=())


def test_consensus_window_is_relative_with_an_absolute_floor() -> None:
    """Both halves are load-bearing and the floor was bought by a failure.

    A purely relative window asks the wrong question when the fit is exact: the
    synthetic ladder converges to cost ~1e-29, ``1.5x`` of which admits nothing but the
    winner, and a *perfect* recovery was refused for lack of anyone to agree with.
    """
    from softae.analysis.eis import constrained_fit as module

    assert CONSENSUS_COST_FACTOR > 1.0
    assert module.EXACT_COST_PER_RESIDUAL > 0.0
    # The floor must be far below any measured spectrum's cost per residual: the four
    # NIST standards fit at ~0.25 over ~320 residuals, i.e. ~8e-4 per residual.
    assert module.EXACT_COST_PER_RESIDUAL < 1e-6


# ── The plausibility band on Qg ──────────────────────────────────────────────

def test_qg_ceiling_sits_between_the_two_measured_populations() -> None:
    """The constant is a position in a gap, so the test is that it is still in it.

    Widest ``Qg`` ever *returned* by a good fit across eleven subsets of the four NIST
    standards on two preparations: 1.048e-9. Lowest ``Qg`` from the poisoned basin
    across four routes and three preparations: 8.418e-8. An edit that moves the ceiling
    out of that window changes what the refusal means, and should have to say so here.
    """
    assert 1.048e-9 < QG_PLAUSIBLE_MAX < 8.418e-8


def test_implausible_shared_passes_a_good_artifact(artifact) -> None:
    assert implausible_shared(artifact) == ""
    assert artifact.Qg < QG_PLAUSIBLE_MAX


def test_implausible_shared_names_the_ceiling_it_refused_on(artifact) -> None:
    reason = implausible_shared(artifact, max_qg=artifact.Qg / 2.0)
    assert "plausible ceiling" in reason
    assert f"{artifact.Qg:.4g}" in reason


def test_implausible_shared_treats_a_nan_qg_as_a_failure_not_a_pass() -> None:
    """NaN fails every comparison, so ``Qg > ceiling`` alone would let it through."""
    assert implausible_shared(
        SharedArtifact(Qg=float("nan"), ng=0.95, nd=0.76)) .startswith("Qg is NaN")


def test_implausible_shared_can_be_switched_off_only_explicitly(artifact) -> None:
    assert implausible_shared(artifact, max_qg=math.inf) == ""
    assert implausible_shared(SharedArtifact(Qg=1.0, ng=0.95, nd=0.76),
                              max_qg=math.inf) == ""


def test_fit_shared_refuses_an_artifact_above_the_qg_ceiling(ladder) -> None:
    """End to end, and the control is the same call with the ceiling lifted.

    The synthetic ladder's true ``Qg`` is 1.2e-9, so the band is exercised by moving the
    ceiling under it rather than by manufacturing a bad fit — the real poisoned basin is
    not reachable from spectra the forward model generated exactly, which is why the
    discriminating version of this test is the answer-key one.
    """
    permitted = fit_shared(ladder, max_qg=math.inf, **FAST)
    assert permitted.Qg == pytest.approx(TRUE_SHARED["Qg"], rel=1e-3)

    with pytest.raises(ImplausibleArtifact, match="plausible ceiling") as exc:
        fit_shared(ladder, max_qg=permitted.Qg / 2.0, **FAST)
    # The artifact travels in the message; a refusal that says nothing about what it saw
    # is a dead end for whoever reads the log.
    assert "artifact from" in str(exc.value)


def test_implausible_artifact_is_recorded_as_a_refused_fold(ladder) -> None:
    assert issubclass(ImplausibleArtifact, InadmissibleFitSet)
    report = holdout_report(ladder, kind="leave_one_out", max_qg=1e-12,
                            max_mean_abs_error_pct=math.inf, **FAST)
    assert len(report.refused) == len(ladder)
    assert all("plausible ceiling" in reason for _, reason in report.refused)


# ── R_sol = R0 + R1, unconditionally ─────────────────────────────────────────

def test_r_sol_is_the_sum_not_the_bulk_term(ladder, artifact) -> None:
    for spec in ladder:
        fit = fit_frozen(spec, artifact)
        assert fit.R_sol == fit.R0 + fit.R1
        # R1 alone is short of the truth by the whole series term, which is the
        # sigma-dependent shortfall the sum exists to avoid.
        assert fit.R1 < spec.reference_ohm * 0.95


def test_r_sol_is_reported_even_when_the_split_is_unidentifiable() -> None:
    """No rho test, no split-vs-sum branch: the sum is always what comes out.

    A spectrum whose series term is a thousandth of the total cannot support the
    split, and this is exactly the case the legacy path declines to report.
    """
    spec = synth("tiny_series", 50_000.0)
    spec = ConstrainedSpectrum(
        label="tiny_series", freq_hz=spec.freq_hz,
        z=model_impedance(spec.freq_hz,
                          {**TRUE_SHARED, "R0": 50.0, "R1": 49_950.0, "Qd": 2e-6},
                          spec.y_shunt, 0.0),
        y_shunt=spec.y_shunt, reference_ohm=50_000.0)
    artifact = fit_shared([spec, *[synth(k, v) for k, v in TRUE_R_SOL.items()]],
                          **FAST)
    fit = fit_frozen(spec, artifact)
    assert fit.R_sol == pytest.approx(50_000.0, rel=1e-2)


# ── The pinned inductance ────────────────────────────────────────────────────

def test_pinned_inductance_is_consumed_not_fitted() -> None:
    """A spectrum built with a real lead L is recovered when L is pinned to it."""
    l_lead = 1.7294984432805884e-06          # mux16 L_lead_H, ch25
    specs = [synth(k, v, pinned_l_H=l_lead) for k, v in TRUE_R_SOL.items()]
    artifact = fit_shared(specs, **FAST)
    for name, truth in TRUE_SHARED.items():
        assert getattr(artifact, name) == pytest.approx(truth, rel=1e-3), name
    for spec in specs:
        assert fit_frozen(spec, artifact).R_sol == pytest.approx(
            spec.reference_ohm, rel=1e-3)


def test_wrong_pinned_inductance_moves_the_answer() -> None:
    """The positive control for the test above: pinning L must actually do something.

    Without this, ``test_pinned_inductance_is_consumed_not_fitted`` would pass just as
    happily if ``pinned_l_H`` were ignored entirely — SUBAGENT_RULES §3.1(e).
    """
    l_lead = 5e-4                            # far larger than any real lead
    truth = np.array([model_impedance(np.array([2.0e5]),
                                      {**TRUE_SHARED, "R0": 120.0, "R1": 680.0,
                                       "Qd": 2e-6},
                                      np.zeros(1, dtype=complex), L)[0]
                      for L in (0.0, l_lead)])
    assert abs(truth[1] - truth[0]) > 1.0


def test_l_is_not_a_bounded_parameter_anywhere() -> None:
    spec = synth("one", 10_000.0)
    assert spec.pinned_l_H == 0.0
    # It travels on the spectrum, not in the fit's box constraints.
    assert "pinned_l_H" in spec.__dataclass_fields__


# ── G_fixture, consumed point by point ───────────────────────────────────────

def _dielectric_table(n: int = 20) -> FixtureConductance:
    """``G = ωC·tanδ`` — this fixture's measured shape, ``d ln G/d ln f`` ≈ 1."""
    f = np.logspace(math.log10(14.28), math.log10(2.0e5), n)
    g = 2.0 * math.pi * f * 5.3e-11 * 0.05
    return FixtureConductance(freq_hz=tuple(f), G_S=tuple(g), exponent=1.0)


def test_fixture_admittance_is_evaluated_per_frequency_not_collapsed() -> None:
    table = _dielectric_table()
    freq = np.logspace(math.log10(20.0), math.log10(1.0e5), 25)
    shunt = fixture_admittance(freq, table, 0.0)
    assert isinstance(shunt, ShuntTable)
    assert shunt.y.shape == freq.shape
    # A scalar would give one value repeated. This spans three decades, monotonically,
    # because on this fixture the loss is dielectric.
    real = shunt.y.real
    assert np.all(np.diff(real) > 0)
    assert real[-1] / real[0] > 1e3


def test_fixture_admittance_adds_the_stray_capacitance_as_reactance() -> None:
    """``beyond_coverage="zero"`` is load-bearing here, not decoration.

    A caller with a stray capacitance and no conductance table is exactly the case
    :class:`UnmeasuredFixtureShunt` refuses, so this test has to *declare* that the
    conductance is absent on purpose. Before 2026-09-08 it passed ``None`` and said
    nothing, which is the same silence a channel with no ``G_fixture`` would have made.
    """
    freq = np.array([100.0, 1000.0])
    shunt = fixture_admittance(freq, None, 5.3e-11, beyond_coverage="zero")
    assert np.allclose(shunt.y.real, 0.0)
    assert shunt.y.imag == pytest.approx(2 * math.pi * freq * 5.3e-11)
    # And the table says the conductance was never measured, rather than measured to be
    # zero everywhere: a fully covered spectrum reports the opposite of this.
    assert shunt.n_held == shunt.n_points == 2
    assert shunt.held_fraction == 1.0


def test_fixture_admittance_reports_points_beyond_the_measured_band() -> None:
    """Blocker 4. Holding the endpoint is a decision, so it is counted and logged."""
    table = _dielectric_table()
    freq = np.logspace(math.log10(1.2), math.log10(2.0e5), 40)   # starts below 14.28 Hz
    held = fixture_admittance(freq, table, 0.0, beyond_coverage="hold")
    assert held.n_held > 0
    assert held.coverage_hz[0] == pytest.approx(14.28, rel=1e-3)
    below = freq < held.coverage_hz[0]
    assert np.allclose(held.y.real[below], table.G_S[0])
    assert 0.0 < held.held_fraction < 1.0


def test_fixture_admittance_drop_policy_emits_nan_for_uncovered_points() -> None:
    table = _dielectric_table()
    freq = np.logspace(math.log10(1.2), math.log10(2.0e5), 40)
    dropped = fixture_admittance(freq, table, 0.0, beyond_coverage="drop")
    below = freq < dropped.coverage_hz[0]
    assert np.all(np.isnan(dropped.y.real[below]))
    assert np.all(np.isfinite(dropped.y.real[~below]))
    assert dropped.n_held == int(np.count_nonzero(below))


def test_fixture_admittance_rejects_an_unknown_policy() -> None:
    with pytest.raises(ValueError, match="beyond_coverage"):
        fixture_admittance(np.array([100.0]), _dielectric_table(), 0.0,
                           beyond_coverage="wing it")


def test_an_absent_conductance_table_is_refused_rather_than_treated_as_zero() -> None:
    """The refusal. Before it, this call returned a shunt of exactly zero and a
    ``ShuntTable`` reporting ``n_held = 0`` — full coverage of nothing."""
    freq = np.logspace(1.0, 5.0, 20)
    with pytest.raises(UnmeasuredFixtureShunt, match="no G_fixture"):
        fixture_admittance(freq, None, 5.3e-11)


def test_an_empty_conductance_table_is_refused_the_same_as_none() -> None:
    """A ``FixtureConductance`` with no rows is the shape ``from_dict`` produces for a
    channel whose open blank was unusable, and it must not read as a measurement."""
    empty = FixtureConductance(freq_hz=(), G_S=())
    assert empty.is_empty
    with pytest.raises(UnmeasuredFixtureShunt):
        fixture_admittance(np.logspace(1.0, 5.0, 20), empty, 0.0)


def test_the_shunt_refusal_is_in_the_modules_own_refusal_hierarchy() -> None:
    """One idiom, not four. Every refusal in this module is an
    :class:`InadmissibleFitSet`, so a caller that wants to catch all of them catches
    one type — and a ``ValueError`` handler written before this existed still works."""
    assert issubclass(UnmeasuredFixtureShunt, InadmissibleFitSet)
    assert issubclass(UnmeasuredFixtureShunt, ValueError)


def test_the_refusal_names_the_way_out_of_it() -> None:
    """A refusal with no stated escape gets worked around rather than answered."""
    with pytest.raises(UnmeasuredFixtureShunt) as excinfo:
        fixture_admittance(np.logspace(1.0, 5.0, 8), None, 0.0)
    assert "beyond_coverage='zero'" in str(excinfo.value)


def test_a_declared_absent_shunt_is_distinguishable_from_a_measured_one() -> None:
    """The point of the whole item: the two cases must not produce the same record.

    ``held_fraction`` is what a consumer would read to ask "how much of this was
    measured?", and until 2026-09-08 both answers were 0.0.
    """
    freq = np.logspace(math.log10(20.0), math.log10(1.0e5), 25)
    declared = fixture_admittance(freq, None, 0.0, beyond_coverage="zero")
    measured = fixture_admittance(freq, _dielectric_table(), 0.0)

    assert declared.held_fraction == 1.0
    assert measured.held_fraction == 0.0
    assert np.allclose(declared.y, 0.0)
    assert np.all(measured.y.real > 0.0)


def test_an_unknown_policy_is_rejected_even_with_no_table_to_apply_it_to() -> None:
    """The policy check is hoisted, so the two refusals cannot mask each other: a
    caller who typoed the opt-out hears about the typo, not about the missing table."""
    assert "zero" in BEYOND_COVERAGE_POLICIES
    with pytest.raises(ValueError, match="beyond_coverage"):
        fixture_admittance(np.array([100.0]), None, 0.0, beyond_coverage="zeroo")


def test_the_refused_shape_is_what_the_live_calibration_hands_a_sample_channel() -> None:
    """``SUBAGENT_RULES`` §3.1(e) — production must be able to produce what is injected.

    ``CalibrationSet.G_fixture`` is a ``dict[int, FixtureConductance]``, so an unlisted
    channel yields ``None`` from a plain ``.get`` — the exact argument the refusal fires
    on. The mapping below mirrors ``eis_calibrations`` id 23 (``mux16``, 2026-09-03),
    which carries ``G_fixture`` for channels 17-23 and 25 and for no other, while 3 538
    of the corpus's 3 872 ``role='sample'`` rows sit on channels that have none.
    """
    calibration = CalibrationSet(
        fixture_id="mux16", created_at="2026-09-03",
        G_fixture={ch: _dielectric_table() for ch in (17, 18, 19, 20, 21, 22, 23, 25)},
    )
    freq = np.logspace(math.log10(20.0), math.log10(1.0e5), 25)

    assert calibration.G_fixture.get(25) is not None
    assert fixture_admittance(freq, calibration.G_fixture.get(25), 0.0).n_held == 0

    assert calibration.G_fixture.get(1) is None, "the premise of the refusal"
    with pytest.raises(UnmeasuredFixtureShunt):
        fixture_admittance(freq, calibration.G_fixture.get(1), 0.0)


def test_known_shunt_is_recovered_through_the_fit_not_absorbed() -> None:
    """A spectrum built *with* a fixture shunt is only recovered when it is supplied.

    The positive control that the shunt reaches the model: fitting the same spectrum
    with the shunt zeroed gives a materially different ``R_sol``.
    """
    table = _dielectric_table()
    specs, blind = [], []
    for label, r_sol in TRUE_R_SOL.items():
        freq = np.logspace(math.log10(14.28), math.log10(2.0e5), 40)
        y = fixture_admittance(freq, table, 5.3e-11).y
        params = {**TRUE_SHARED, "R0": 0.15 * r_sol, "R1": 0.85 * r_sol, "Qd": 2e-6}
        z = model_impedance(freq, params, y, 0.0)
        specs.append(ConstrainedSpectrum(label, freq, z, y, reference_ohm=r_sol))
        blind.append(ConstrainedSpectrum(label, freq, z, np.zeros(40, dtype=complex),
                                         reference_ohm=r_sol))

    supplied = fit_shared(specs, **FAST)
    for spec in specs:
        assert fit_frozen(spec, supplied).R_sol == pytest.approx(
            spec.reference_ohm, rel=1e-3), spec.label

    ignored = fit_shared(blind, **FAST)
    worst = max(abs(fit_frozen(s, ignored).R_sol / s.reference_ohm - 1.0)
                for s in blind)
    assert worst > 0.01, "zeroing the shunt changed nothing — it is not reaching the model"


# ── Admissibility: a refusal is a result ─────────────────────────────────────

def test_arc_is_resolved_detects_the_crossover_in_band() -> None:
    resolved = synth("wide", 70_000.0, band=(4.0, 2.0e5))
    assert arc_is_resolved(resolved.freq_hz, resolved.z)
    # Truncate away the low-frequency blocking tail and the crossover leaves the band.
    lo = synth("high_only", 70_000.0, band=(2.0e4, 2.0e5))
    assert not arc_is_resolved(lo.freq_hz, lo.z)


def test_arc_is_resolved_is_false_for_too_few_points() -> None:
    assert not arc_is_resolved(np.array([1.0, 2.0]), np.array([1 - 1j, 1 - 2j]))


def test_check_admissible_refuses_a_set_with_no_arc_resolved_spectrum() -> None:
    blind = [synth(f"high_only_{i}", r, band=(2.0e4, 2.0e5))
             for i, r in enumerate((38_000.0, 2_400.0))]
    verdict = check_admissible(blind)
    assert isinstance(verdict, Admissibility)
    assert not verdict.admissible
    assert verdict.n_arc_resolved == 0
    assert verdict.arc_resolved == ()
    assert "resolve the geometric arc" in verdict.reason


def test_check_admissible_accepts_a_set_with_one_arc_resolved_spectrum() -> None:
    """The recalibration from 2 to 1, asserted as behaviour rather than as a constant.

    Measured on the four NIST standards with this gate bypassed: sets with **one**
    arc-resolved member score ``R_sol`` MAE 3.06–4.39 % against 3.00–4.28 % for sets
    with two — interleaved, not merely close — while the one set with **none** scores
    2338 %. See :func:`~softae.analysis.eis.constrained_fit.check_admissible`.
    """
    assert MIN_ARC_RESOLVED == 1
    one = [synth("wide", 70_000.0, band=(4.0, 2.0e5)),
           *(synth(f"high_only_{i}", r, band=(2.0e4, 2.0e5))
             for i, r in enumerate((38_000.0, 2_400.0)))]
    verdict = check_admissible(one)
    assert verdict.n_arc_resolved == 1
    assert verdict.admissible, verdict.describe()
    # And the threshold is still a threshold: ask for two and the same set is refused.
    assert not check_admissible(one, min_arc_resolved=2).admissible


def test_fit_shared_raises_rather_than_returning_a_bad_artifact() -> None:
    """Blocker 2. The refusal is the deliverable, not a degraded number."""
    blind = [synth(f"high_only_{i}", r, band=(2.0e4, 2.0e5))
             for i, r in enumerate((38_000.0, 2_400.0))]
    with pytest.raises(InadmissibleFitSet, match="INADMISSIBLE"):
        fit_shared(blind)


def test_check_admissible_refuses_a_single_spectrum() -> None:
    verdict = check_admissible([synth("only", 10_000.0)])
    assert not verdict.admissible
    assert "at least two spectra" in verdict.reason


def test_check_admissible_accepts_the_ladder(ladder) -> None:
    verdict = check_admissible(ladder)
    assert verdict.admissible
    assert verdict.n_arc_resolved >= 2
    assert verdict.n_residuals > verdict.n_free


def test_admissibility_travels_on_the_artifact(artifact) -> None:
    assert artifact.admissibility is not None
    assert artifact.admissibility.admissible


# ── Blocker 1: the tolerance is load-bearing ─────────────────────────────────

def test_constrained_fit_tol_is_far_tighter_than_the_scipy_default() -> None:
    assert CONSTRAINED_FIT_TOL <= 1e-12


def test_loose_tolerance_stops_short_of_the_minimum() -> None:
    """The stacked fit at scipy's default terminates *reporting success*.

    Measured on the real NIST set the gap is 8014 % against 1.56 %. Synthetically the
    gap is smaller — noise-free data is kind — so the assertion is on the cost the
    optimiser reached, which is the quantity that is actually wrong, and on the fact
    that the loose run still reports a successful status.
    """
    ladder = [synth(k, v) for k, v in TRUE_R_SOL.items()]
    loose = fit_shared(ladder, tol=1e-8, **FAST)
    tight = fit_shared(ladder, tol=CONSTRAINED_FIT_TOL, **FAST)
    assert tight.cost < loose.cost
    assert loose.status > 0, "the loose run reports success — that is the whole problem"
    assert tight.tol == CONSTRAINED_FIT_TOL and loose.tol == 1e-8


def test_loose_tolerance_is_warned_about(monkeypatch) -> None:
    """Asserted on the logger call, not on log capture — structlog routing varies."""
    from softae.analysis.eis import constrained_fit as module

    events: list[tuple[str, dict]] = []
    monkeypatch.setattr(
        module.logger, "warning",
        lambda event, **kw: events.append((event, kw)))
    fit_shared([synth(k, v) for k, v in TRUE_R_SOL.items()], tol=1e-6, **FAST)
    assert [e for e, _ in events] == ["eis_constrained_fit_loose_tolerance"]
    assert events[0][1]["tol"] == 1e-6


def test_tight_tolerance_is_not_warned_about(monkeypatch) -> None:
    """The negative half. Without it the test above cannot distinguish a warning that
    fires on the loose case from one that fires unconditionally."""
    from softae.analysis.eis import constrained_fit as module

    events: list[str] = []
    monkeypatch.setattr(module.logger, "warning",
                        lambda event, **kw: events.append(event))
    fit_shared([synth(k, v) for k, v in TRUE_R_SOL.items()], **FAST)
    assert events == []


def test_tolerance_reaches_the_optimiser(monkeypatch) -> None:
    """Positive control: the keyword must actually arrive at ``least_squares``.

    Without this the test above could pass on two runs that both used the default —
    SUBAGENT_RULES §3.1(e).
    """
    from softae.analysis.eis.constrained_fit import fit as module

    seen: list[float] = []
    real = module.least_squares

    def spy(*args, **kwargs):
        seen.append(kwargs.get("ftol"))
        return real(*args, **kwargs)

    monkeypatch.setattr(module, "least_squares", spy)
    fit_shared([synth(k, v) for k, v in TRUE_R_SOL.items()], tol=1e-9, **FAST)
    assert seen and set(seen) == {1e-9}


# ── Blocker 3: multi-start ───────────────────────────────────────────────────

def test_multistart_grid_spans_decades_either_side_of_the_estimate() -> None:
    assert min(R_SOL_SEED_MULTIPLIERS) <= 0.1
    assert max(R_SOL_SEED_MULTIPLIERS) >= 100.0
    assert 1.0 in R_SOL_SEED_MULTIPLIERS


def test_fit_frozen_reports_its_seed_spread(ladder, artifact) -> None:
    """A good artifact is seed-insensitive, and the spread is how that is known."""
    fit = fit_frozen(ladder[0], artifact)
    assert fit.seed_spread_pct == pytest.approx(0.0, abs=1e-6)
    assert fit.seed_multiplier in R_SOL_SEED_MULTIPLIERS


def test_fit_frozen_recovers_from_a_deliberately_bad_single_seed(ladder, artifact) -> None:
    spec = ladder[0]
    only_bad = fit_frozen(spec, artifact, multipliers=(0.001,))
    every = fit_frozen(spec, artifact, multipliers=R_SOL_SEED_MULTIPLIERS)
    assert every.cost <= only_bad.cost
    assert every.R_sol == pytest.approx(spec.reference_ohm, rel=1e-3)


# ── Validation surface ───────────────────────────────────────────────────────

def test_holdout_result_error_is_signed_relative_percent() -> None:
    assert HoldoutResult("x", 100.0, 110.0).error_pct == pytest.approx(10.0)
    assert HoldoutResult("x", 100.0, 90.0).error_pct == pytest.approx(-10.0)
    assert math.isnan(HoldoutResult("x", 0.0, 1.0).error_pct)


def test_holdout_report_in_sample_scores_every_reference(ladder) -> None:
    report = holdout_report(ladder, kind="in_sample", **FAST)
    assert report.kind == "in_sample"
    assert len(report.results) == len(ladder)
    assert report.mean_abs_error_pct < 1.0
    assert report.refused == ()


def test_holdout_report_leave_one_out_scores_only_held_out_spectra(ladder) -> None:
    report = holdout_report(ladder, kind="leave_one_out", **FAST)
    assert report.kind == "leave_one_out"
    assert len(report.results) + len(report.refused) == len(ladder)
    assert report.worst_abs_error_pct >= report.mean_abs_error_pct


def test_holdout_report_records_refused_folds_rather_than_skipping_them() -> None:
    """A fold dropped for inadmissibility must be visible, not averaged away."""
    good = synth("wide", 70_000.0)
    blind = [synth(f"high_only_{i}", r, band=(2.0e4, 2.0e5))
             for i, r in enumerate((38_000.0, 2_400.0))]
    report = holdout_report([good, *blind], kind="leave_one_out", **FAST)
    refused = {label for label, _ in report.refused}
    # Holding out the only arc-resolved spectrum leaves a set that resolves none.
    assert refused == {"wide"}
    assert "INADMISSIBLE" in dict(report.refused)["wide"]
    assert "refused" in report.describe()


def test_holdout_report_rejects_an_unknown_kind(ladder) -> None:
    with pytest.raises(ValueError, match="unknown holdout kind"):
        holdout_report(ladder, kind="optimistic", **FAST)


# ── The generalisation gate ──────────────────────────────────────────────────

def _report(kind: str, *errors_pct: float) -> HoldoutReport:
    """A report with known errors, so the gate can be tested without running a fit."""
    return HoldoutReport(kind, tuple(HoldoutResult(f"s{i}", 100.0, 100.0 + e)
                                     for i, e in enumerate(errors_pct)))


def test_refuse_unless_generalises_returns_a_report_that_passes() -> None:
    good = _report("leave_one_out", 3.0, -6.0, 1.0)
    assert refuse_unless_generalises(good) is good


def test_refuse_unless_generalises_raises_above_the_threshold() -> None:
    with pytest.raises(PoorGeneralisation, match="mean .error.") as exc:
        refuse_unless_generalises(_report("leave_one_out", 40.0, -60.0))
    assert "generalisation" in str(exc.value)
    assert issubclass(PoorGeneralisation, InadmissibleFitSet)


def test_refuse_unless_generalises_says_when_the_number_is_only_in_sample() -> None:
    """``kind`` is load-bearing and the refusal message is where it is spent."""
    with pytest.raises(PoorGeneralisation, match="weaker claim"):
        refuse_unless_generalises(_report("in_sample", 40.0, -60.0))


def test_refuse_unless_generalises_refuses_when_nothing_could_be_scored() -> None:
    """SUBAGENT_RULES §3.1(a): "could not judge" must not be spelled "clean"."""
    nothing = HoldoutReport("leave_one_out", (), (("a", "refused"),))
    assert math.isnan(nothing.mean_abs_error_pct)
    with pytest.raises(PoorGeneralisation, match="unjudged rather than acceptable"):
        refuse_unless_generalises(nothing)


def test_generalisation_threshold_is_between_the_measured_populations() -> None:
    """Good leave-one-out 3.04 %, poisoned-basin leave-one-out 39.97 %, on the four
    NIST standards. The threshold has to sit between them or it is not a threshold."""
    assert 6.4 < HOLDOUT_REFUSE_PCT < 39.9


def test_holdout_report_applies_the_gate_by_default(ladder) -> None:
    """The wiring, with a control that proves the gate is what changed the outcome.

    The fit is unchanged; only the answer key is moved. Declaring each spectrum's
    reference to be twice its true ``R_sol`` makes every holdout error ~50 %, which is
    above the shipped threshold and nowhere near it with the threshold lifted — so a
    green result here cannot come from the fit having failed.
    """
    lying = [ConstrainedSpectrum(s.label, s.freq_hz, s.z, s.y_shunt,
                                 reference_ohm=2.0 * s.reference_ohm) for s in ladder]

    permitted = holdout_report(lying, kind="in_sample",
                               max_mean_abs_error_pct=math.inf, **FAST)
    assert permitted.mean_abs_error_pct == pytest.approx(50.0, abs=1.0)

    with pytest.raises(PoorGeneralisation, match="exceeds 25%"):
        holdout_report(lying, kind="in_sample", **FAST)


# ── Housekeeping ─────────────────────────────────────────────────────────────

def test_constrained_spectrum_rejects_mismatched_array_lengths() -> None:
    with pytest.raises(ValueError, match="points against"):
        ConstrainedSpectrum("bad", np.arange(5.0), np.zeros(4, dtype=complex),
                            np.zeros(5, dtype=complex))


def test_conductance_r_sol_reads_a_pure_resistor() -> None:
    z = np.full(10, 4700.0 + 0j)
    assert conductance_r_sol(np.logspace(1, 5, 10), z) == pytest.approx(4700.0)


def test_artifact_railed_names_a_parameter_resting_on_a_bound() -> None:
    from softae.analysis.eis.constrained_fit import SharedArtifact

    assert SharedArtifact(Qg=1e-9, ng=0.9, nd=0.8).railed() == ()
    assert SharedArtifact(Qg=1e-9, ng=0.9, nd=BOUNDS["nd"][1]).railed() == ("nd",)


def test_module_is_not_wired_into_any_live_path() -> None:
    """It ships inert. This test is what makes that a contract rather than a comment.

    Read off the **import graph**, not off the text. The substring version of this test
    was fooled the first time another module mentioned this one in a docstring
    (``conditioning.py``, which names it precisely to say it is inert) — a false failure
    on correct work, which is the direction that teaches people to override a check. An
    ``ast`` walk sees imports and dynamic-import strings and does not see prose.
    """
    import ast

    def imports_it(path: Path) -> bool:
        # ``utf-8-sig``: several GUI modules in this tree carry a BOM, and ``ast.parse``
        # rejects the U+FEFF that plain ``utf-8`` decoding leaves at the front.
        tree = ast.parse(path.read_text(encoding="utf-8-sig"))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                if any("constrained_fit" in a.name for a in node.names):
                    return True
            elif isinstance(node, ast.ImportFrom):
                if "constrained_fit" in (node.module or "") or \
                        any(a.name == "constrained_fit" for a in node.names):
                    return True
            elif isinstance(node, ast.Constant) and isinstance(node.value, str):
                # importlib.import_module("…eis.constrained_fit") and friends.
                if "eis.constrained_fit" in node.value:
                    return True
        return False

    src = Path(__file__).resolve().parents[1] / "src" / "softae"
    # What the ``p.name != "constrained_fit.py"`` exclusion became when the module
    # became a package: the package's own siblings import each other, and must not read
    # as importers of it. They do so *relatively* — ``from .model import ...`` — which
    # the walk above already does not match, so this is belt to that braces; it is here
    # so that an absolute intra-package import would not silently fail the contract
    # either. Everything outside the package is scanned exactly as before.
    pkg = src / "analysis" / "eis" / "constrained_fit"
    importers = [str(p) for p in src.rglob("*.py")
                 if not p.is_relative_to(pkg) and imports_it(p)]
    assert importers == [], f"constrained_fit is imported by {importers}"


# ── Answer keys. Real data; skipped when it is not here ──────────────────────

AMP_KCL = Path(r"C:\Users\Osuji\AppData\Local\Programs\Python\Python311\Scripts"
               r"\AMP_v1\data\calibration\2026_0616")
#: R_sol from AMP_v1's own constrained artifact, which scores 1.15 % against NIST.
AMP_R_SOL = {"kcl_45uS": 71007.64, "kcl_84uS": 37933.07,
             "kcl_1413uS": 2347.67, "kcl_4500uS": 775.56}


def _truncate_hf_inductive(f: np.ndarray, z: np.ndarray) -> np.ndarray:
    """``gate_hf_inductive``'s rule, applied here: drop the contiguous ``Im Z > 0`` run.

    **Worth having, and NOT a precondition — this docstring said otherwise until
    2026-09-08 and the figure it quoted was retracted.** It claimed 2.9 % with the
    truncation against 6295 % without, on the four NIST standards. That 6295 % was a
    cell of an *ordering* table: it was produced by the order-dependent seeding
    :data:`SHARED_SEED_GRID` replaced, not by the inductive points. Re-measured on the
    multi-start, same preparation both ways: ``R_sol`` **3.544 %** truncated against
    **3.501 %** untruncated, and σ against NIST **0.98 %** against **2.41 %**. So the
    step is worth about 2.5× on σ and nothing at all on ``R_sol`` — a refinement, kept
    on its own merits. See mail ``[a184]`` §2 and the module docstring.

    The *mechanism* still holds directionally: a blocking cell has no inductance of its
    own, so an ``Im Z > 0`` point at the top of the band is the fixture's lead — and
    left in, the optimiser absorbs it into ``Qg``, which is a shared parameter, so a
    handful of points at one end of one spectrum degrades the artifact for the whole
    set. What did not survive is the claim that the consequence is catastrophic.

    The rule lives in :func:`~softae.analysis.eis.gates.gate_hf_inductive` and already
    ships in the gated engine; it is restated here rather than imported so this test
    exercises the fit rather than the gate's signature.
    """
    keep = np.ones(f.size, dtype=bool)
    for i in np.argsort(f)[::-1]:
        if z.imag[i] > 0:
            keep[i] = False
        else:
            break
    return keep


def _load_amp_csv(path: Path) -> tuple[np.ndarray, np.ndarray]:
    freq, real, neg_imag = [], [], []
    for line in path.read_text().splitlines():
        s = line.strip()
        if not s or s.startswith("#") or s.startswith("frequency"):
            continue
        a, b, c = s.split(",")[:3]
        freq.append(float(a))
        real.append(float(b))
        neg_imag.append(float(c))
    f = np.asarray(freq)
    z = np.asarray(real) - 1j * np.asarray(neg_imag)
    order = np.argsort(f)
    return f[order], z[order]


def _amp_standards(*, truncate_hf: bool = False) -> list[ConstrainedSpectrum]:
    """The four NIST standards, loaded once in one place.

    The preparation is deliberately thinner than the offline harness's — no short-blank
    correction, no |Z| window, no linear-KK truncation, ``L`` pinned to 0 — so what these
    tests exercise is the fit rather than a conditioning chain that does not ship in
    ``src/`` at all.
    """
    specs = []
    for label, ref in AMP_R_SOL.items():
        f, z = _load_amp_csv(AMP_KCL / f"{label}.csv")
        keep = np.isfinite(z) & (z.real > 0)
        if truncate_hf:
            keep = keep & _truncate_hf_inductive(f, z)
        specs.append(ConstrainedSpectrum(label, f[keep], z[keep],
                                         np.zeros(int(keep.sum()), dtype=complex),
                                         reference_ohm=ref))
    return specs


#: Two grid entries in the poisoned basin — ``Qg`` three decades high, ``nd`` near 0.34.
#: Restricting the multi-start to them is how a *poisoned artifact* is produced on
#: purpose now that ordering cannot produce one: measured on the four standards they
#: reach costs within 1.5x of each other and ``R_sol`` values 1.95e5 % apart.
POISONED_STARTS = (SHARED_SEED_GRID[8], SHARED_SEED_GRID[9])


@pytest.mark.skipif(not AMP_KCL.is_dir(), reason="AMP_v1 NIST standards not present")
def test_answer_key_nist_standards_split_admissible_from_inadmissible_folds() -> None:
    """The gate fires on the set that resolves **no** arc, and on nothing else here.

    This is the recalibrated partition and it is the reason the recalibration was worth
    doing. At ``MIN_ARC_RESOLVED = 2`` every leave-one-out fold that dropped
    ``kcl_45uS`` or ``kcl_84uS`` was refused, so the module's only generalisation number
    was computed on **two of four folds** while the other two were recorded as
    unjudgeable — and re-measurement put those two at −6.4 % / −2.5 %, no worse than the
    folds it kept. At 1 all four folds are scored. The refusal has not been given up:
    ``kcl_1413uS + kcl_4500uS``, the one subset of this corpus with no arc-resolved
    member, is still refused, and its artifact is the reason — ``Qg`` 1.3e-07 and
    ``R_sol`` wrong by 2338 %.
    """
    specs = _amp_standards()

    verdict = {s.label: arc_is_resolved(s.freq_hz, s.z) for s in specs}
    assert verdict == {"kcl_45uS": True, "kcl_84uS": True,
                       "kcl_1413uS": False, "kcl_4500uS": False}

    report = holdout_report(specs, kind="leave_one_out", **FAST)
    assert report.refused == (), report.describe()
    assert {r.label for r in report.results} == set(verdict)
    # And all four folds together clear the generalisation gate, which is the point of
    # scoring them: at the full seed grid this is 3.04 % mean / 6.37 % worst.
    assert report.mean_abs_error_pct < HOLDOUT_REFUSE_PCT, report.describe()

    blind = [s for s in specs if not verdict[s.label]]
    assert not check_admissible(blind).admissible
    with pytest.raises(InadmissibleFitSet, match="resolve the geometric arc"):
        fit_shared(blind, **FAST)


@pytest.mark.skipif(not AMP_KCL.is_dir(), reason="AMP_v1 NIST standards not present")
def test_answer_key_one_artifact_for_every_order_of_the_same_standards(
        monkeypatch) -> None:
    """Order invariance **on the corpus where order dependence was measured.**

    The synthetic version of this test cannot discriminate and says so: spectra the
    forward model generated exactly give a surface the retired continuation navigates
    identically from either end. Real spectra do not, and the control half below is the
    proof — the same four standards, the same optimiser, the same tolerance, only the
    seeding put back, land 88x apart in ``Qg`` and at ``R_sol`` MAE 2.06 % against
    8546 % purely by reversing the list.
    """
    specs = _amp_standards(truncate_hf=True)
    orders = ((0, 1, 2, 3), (3, 2, 1, 0))

    artifacts = [fit_shared([specs[i] for i in o], **FAST) for o in orders]
    for other in artifacts[1:]:
        assert other.labels == artifacts[0].labels
        for name, value in other.shared.items():
            assert value == pytest.approx(artifacts[0].shared[name], rel=1e-9), name

    # -- the positive control: the whole fix reverted, in process --
    #
    # Both halves have to come out, and that is the point of doing it here rather than
    # trusting the shape of the code: `_canonical_order` alone would make even the
    # retired seeding order-free, so a control that patched only the seeding would come
    # back green and prove nothing.
    from softae.analysis.eis.constrained_fit import fit as module

    def continuation(spectra, shared, tol):
        """``fit_shared``'s start construction as committed at ``f79e463``."""
        seeds, previous = [], None
        for spec in spectra:
            start = module._seed(spec) if previous is None else dict(previous)
            start.update({p: module._seed(spec)[p] for p in ("R0", "R1")})
            fitted, _ = module._fit_free(spec, start, PARAM_NAMES, tol)
            seeds.append(fitted)
            previous = fitted
        x0 = [float(np.median([s[p] for s in seeds])) for p in SHARED_PARAMS]
        for s in seeds:
            x0 += [s[p] for p in PER_SPECTRUM_PARAMS]
        return x0

    monkeypatch.setattr(module, "_canonical_order", lambda spectra: list(spectra))
    monkeypatch.setattr(module, "_stacked_start", continuation)
    # Both refusals lifted, and the second one is a finding rather than boilerplate:
    # the retired construction drives one of these two orderings to Qg 9.7e-8, which is
    # in the poisoned band, so ImplausibleArtifact fires on the historical defect
    # itself. The control needs the artifact, not the refusal, so both are lifted here.
    continued = [fit_shared([specs[i] for i in o],
                            seed_grid=(SHARED_SEED_GRID[0],),
                            max_order_spread_pct=math.inf, max_qg=math.inf).Qg
                 for o in orders]
    assert max(continued) > 10 * min(continued), (
        "the retired construction returned the same artifact for both orders on the "
        "real corpus, so the invariance assertion above is vacuous")


@pytest.mark.skipif(not AMP_KCL.is_dir(), reason="AMP_v1 NIST standards not present")
def test_answer_key_a_poisoned_artifact_is_refused_rather_than_returned() -> None:
    """The refusal, at the shipped threshold, on real data.

    Ordering can no longer drive the fit into the poisoned basin, so the basin is
    reached the only way left: by restricting the multi-start to it. Both starts
    converge, both report success, ``railed()`` fires on neither — and they disagree
    about ``R_sol`` by 1.95e5 %, which is what
    :data:`~softae.analysis.eis.constrained_fit.ORDER_SPREAD_REFUSE_PCT` is calibrated
    to catch. Without the refusal this returns a confidently wrong number.
    """
    specs = _amp_standards(truncate_hf=True)

    # A bounded per-start budget, and it is a real finding rather than a convenience:
    # aimed at the poisoned basin these two starts take 11 s and 80 s unbounded, which
    # is 93 % of the whole grid's wall time, while winning starts use 34-734 nfev. See
    # `MAX_NFEV_GLOBAL`, which this measurement is part of the case for lowering.
    #
    # The Qg ceiling is lifted because the subject here is the *spread* refusal: this
    # artifact trips both, and the assertions below are about the one that fires first.
    permitted = fit_shared(specs, seed_grid=POISONED_STARTS, max_nfev=4_000,
                           max_order_spread_pct=math.inf, max_qg=math.inf)
    assert permitted.n_consensus == len(POISONED_STARTS)
    assert permitted.railed() == ()
    assert permitted.order_spread_pct > ORDER_SPREAD_REFUSE_PCT

    with pytest.raises(UnstableFitSurface, match="order spread"):
        fit_shared(specs, seed_grid=POISONED_STARTS, max_nfev=4_000)


#: Two starts inside the poisoned basin and **close enough together to agree with each
#: other**. Measured on the four standards: they reach costs within 1.02x, so both are
#: in consensus, and they disagree about ``R_sol`` by ~1-2 % — under
#: :data:`ORDER_SPREAD_REFUSE_PCT` by two orders of magnitude — while the artifact they
#: agree on is wrong by 7689 %. Contrast :data:`POISONED_STARTS`, which straddle the
#: basin and so disagree by 1.96e5 %.
CLUSTERED_POISONED_STARTS = ({"Qg": 4e-8, "ng": 0.95, "nd": 0.85},
                             {"Qg": 8e-8, "ng": 0.95, "nd": 0.85})


@pytest.mark.skipif(not AMP_KCL.is_dir(), reason="AMP_v1 NIST standards not present")
def test_answer_key_the_qg_band_catches_what_the_order_spread_does_not() -> None:
    """The measurement that makes :class:`ImplausibleArtifact` non-redundant.

    The control is the whole test. Reproducibility and correctness are different
    properties, and this is the case that separates them: two descents into the same
    wrong basin agree to ~1 %, ``railed()`` fires on neither, ``status`` reports success
    for both, and the answer is wrong by four orders of magnitude. Every refusal that
    existed before this one passes it.
    """
    specs = _amp_standards(truncate_hf=True)
    # Bounded for the same reason the POISONED_STARTS test is: aimed at this basin, an
    # unbounded start spends minutes. The verdict is stable across 1 000-8 000 nfev.
    bounded = dict(seed_grid=CLUSTERED_POISONED_STARTS, max_nfev=2_000)

    permitted = fit_shared(specs, max_qg=math.inf, **bounded)
    assert permitted.n_consensus == len(CLUSTERED_POISONED_STARTS)
    assert permitted.railed() == ()
    assert permitted.order_spread_pct < ORDER_SPREAD_REFUSE_PCT, (
        "the spread refusal already catches this, so the band proves nothing here")
    assert permitted.Qg > QG_PLAUSIBLE_MAX

    # And it is genuinely wrong, not merely unusual — 1.3e5 % on the most dilute
    # standard against AMP_v1's own artifact.
    worst = max(abs(100.0 * (fit_frozen(s, permitted).R_sol - s.reference_ohm)
                    / s.reference_ohm) for s in specs)
    assert worst > 1_000.0

    with pytest.raises(ImplausibleArtifact, match="plausible ceiling"):
        fit_shared(specs, **bounded)


@pytest.mark.skipif(not AMP_KCL.is_dir(), reason="AMP_v1 NIST standards not present")
def test_answer_key_nist_standards_reproduce_the_constrained_r_sol() -> None:
    """In-sample ``R_sol`` against AMP_v1's constrained artifact: 3.54 % mean here.

    Scored the way that actually matters — σ against NIST after AMP's own two-parameter
    cell-constant calibration — the same fit gives **0.98 % in-sample**, against
    AMP_v1's published 1.15 %; leave-one-out on ``R_sol`` over the two admissible folds
    is 1.46 % mean, 2.81 % worst. The tolerance below is loose on purpose: the claim
    under test is that the constrained fit lands *near* an independent codebase's answer
    on a quantity where an unconstrained fit of the same circuit is off by orders of
    magnitude, not that it reproduces a decimal.

    This runs the full :data:`SHARED_SEED_GRID`, so it is also the accuracy half of the
    order-invariance change. On the offline harness's fuller conditioning, where the two
    are directly comparable, the retired continuation scored σ 1.43 % in-sample /
    3.04 % leave-one-out for its **best** ordering of these four spectra and worse for
    fifteen of the other twenty-three; the multi-start scores 1.13 % / 2.41 % for all
    twenty-four.
    """
    specs = _amp_standards(truncate_hf=True)
    report = holdout_report(specs, kind="in_sample")
    assert report.mean_abs_error_pct < 10.0, report.describe()
    assert report.worst_abs_error_pct < 15.0, report.describe()
