"""Tests for the constrained global fit.

The core assertions **synthesise spectra from the forward model** rather than reading
anything off disk, so they hold on a machine with no ``AMP_v1`` beside it and no
DataStore. Ground truth is then exactly known, which is the only way to test a fitter
without inheriting the very estimator being tested.

The two answer-key tests at the bottom read real data and skip cleanly when it is
absent. They exist because a fitter that recovers its own forward model proves only
that the algebra round-trips — ``SUBAGENT_RULES`` §3.2 — and the corpus is what says
whether the branch is reached by anything real.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pytest

from softae.analysis.eis.calibration import FixtureConductance
from softae.analysis.eis.constrained_fit import (
    BOUNDS,
    CONSTRAINED_FIT_TOL,
    CONTINUATION_RESET,
    PARAM_NAMES,
    PER_SPECTRUM_PARAMS,
    R_SOL_SEED_MULTIPLIERS,
    SHARED_PARAMS,
    Admissibility,
    ConstrainedSpectrum,
    HoldoutResult,
    InadmissibleFitSet,
    ShuntTable,
    arc_is_resolved,
    check_admissible,
    conductance_r_sol,
    fit_frozen,
    fit_shared,
    fixture_admittance,
    holdout_report,
    model_impedance,
)

# ── The forward model, and the truth the tests measure against ───────────────

#: One geometry, one interfacial chemistry — the three quantities the design shares.
TRUE_SHARED = {"Qg": 1.2e-9, "ng": 0.92, "nd": 0.76}

#: A conductivity ladder. The values bracket the NIST standards' fitted ``R_sol``.
TRUE_R_SOL = {"dilute_a": 70_000.0, "dilute_b": 38_000.0,
              "mid": 2_400.0, "concentrated": 800.0}

WIDE_BAND = (4.0, 2.0e5)


def synth(
    label: str,
    r_sol: float,
    *,
    band: tuple[float, float] = WIDE_BAND,
    n: int = 40,
    qd: float = 2e-6,
    pinned_l_H: float = 0.0,
    y_shunt: np.ndarray | None = None,
    shared: dict[str, float] | None = None,
) -> ConstrainedSpectrum:
    """A spectrum generated by :func:`model_impedance` itself, with known truth."""
    freq = np.logspace(math.log10(band[0]), math.log10(band[1]), n)
    params = dict(shared or TRUE_SHARED)
    params.update({"R0": 0.15 * r_sol, "R1": 0.85 * r_sol, "Qd": qd})
    ys = np.zeros(n, dtype=complex) if y_shunt is None else np.asarray(y_shunt)
    z = model_impedance(freq, params, ys, pinned_l_H)
    return ConstrainedSpectrum(label=label, freq_hz=freq, z=z, y_shunt=ys,
                               pinned_l_H=pinned_l_H, reference_ohm=r_sol)


@pytest.fixture
def ladder() -> list[ConstrainedSpectrum]:
    return [synth(label, r) for label, r in TRUE_R_SOL.items()]


# ── The split: three shared, three per spectrum, L in neither ────────────────

def test_parameter_split_partitions_names_with_l_pinned_out() -> None:
    assert set(SHARED_PARAMS) | set(PER_SPECTRUM_PARAMS) == set(PARAM_NAMES)
    assert not set(SHARED_PARAMS) & set(PER_SPECTRUM_PARAMS)
    # L is pinned. A pinned quantity in the parameter vector is one bounds edit away
    # from being fitted, which is the defect overhaul F5 recorded.
    assert "L" not in PARAM_NAMES and "L" not in BOUNDS
    # Nor is a leak resistance, which would be degenerate against a supplied shunt.
    assert "Rleak" not in PARAM_NAMES


def test_fit_shared_recovers_the_shared_three_from_the_forward_model(ladder) -> None:
    artifact = fit_shared(ladder)
    for name, truth in TRUE_SHARED.items():
        assert getattr(artifact, name) == pytest.approx(truth, rel=1e-3), name
    assert artifact.labels == tuple(TRUE_R_SOL)
    assert artifact.railed() == ()


def test_fit_shared_shares_one_value_across_every_spectrum(ladder) -> None:
    """The property that distinguishes this from N independent fits."""
    artifact = fit_shared(ladder)
    frozen = artifact.shared
    assert set(frozen) == set(SHARED_PARAMS)
    # Each spectrum's own truth differs in R_sol by ~90x, yet one triple serves all.
    for spec in ladder:
        fit = fit_frozen(spec, artifact)
        assert fit.R_sol == pytest.approx(spec.reference_ohm, rel=1e-3), spec.label


def test_fit_frozen_varies_only_the_per_spectrum_three(ladder) -> None:
    artifact = fit_shared(ladder)
    a = fit_frozen(ladder[0], artifact)
    b = fit_frozen(ladder[-1], artifact)
    # The per-spectrum parameters move with the spectrum...
    assert a.R0 != b.R0 and a.R1 != b.R1
    # ...while the artifact they were fitted against is unchanged by fitting.
    assert artifact.shared == fit_shared(ladder).shared


def test_continuation_reset_names_only_the_resistances() -> None:
    """The seeding rule worth 1.4 % against 28 000 % — see the constant's docstring."""
    assert set(CONTINUATION_RESET) == {"R0", "R1"}
    assert set(CONTINUATION_RESET) <= set(PER_SPECTRUM_PARAMS)


# ── R_sol = R0 + R1, unconditionally ─────────────────────────────────────────

def test_r_sol_is_the_sum_not_the_bulk_term(ladder) -> None:
    artifact = fit_shared(ladder)
    for spec in ladder:
        fit = fit_frozen(spec, artifact)
        assert fit.R_sol == fit.R0 + fit.R1
        # R1 alone is short of the truth by the whole series term, which is the
        # sigma-dependent shortfall the sum exists to avoid.
        assert fit.R1 < spec.reference_ohm * 0.95


def test_r_sol_is_reported_even_when_the_split_is_unidentifiable() -> None:
    """No rho test, no split-vs-sum branch: the sum is always what comes out.

    A spectrum whose series term is a thousandth of the total cannot support the
    split, and this is exactly the case the legacy path declines to report.
    """
    spec = synth("tiny_series", 50_000.0)
    spec = ConstrainedSpectrum(
        label="tiny_series", freq_hz=spec.freq_hz,
        z=model_impedance(spec.freq_hz,
                          {**TRUE_SHARED, "R0": 50.0, "R1": 49_950.0, "Qd": 2e-6},
                          spec.y_shunt, 0.0),
        y_shunt=spec.y_shunt, reference_ohm=50_000.0)
    artifact = fit_shared([spec, *[synth(k, v) for k, v in TRUE_R_SOL.items()]])
    fit = fit_frozen(spec, artifact)
    assert fit.R_sol == pytest.approx(50_000.0, rel=1e-2)


# ── The pinned inductance ────────────────────────────────────────────────────

def test_pinned_inductance_is_consumed_not_fitted() -> None:
    """A spectrum built with a real lead L is recovered when L is pinned to it."""
    l_lead = 1.7294984432805884e-06          # mux16 L_lead_H, ch25
    specs = [synth(k, v, pinned_l_H=l_lead) for k, v in TRUE_R_SOL.items()]
    artifact = fit_shared(specs)
    for name, truth in TRUE_SHARED.items():
        assert getattr(artifact, name) == pytest.approx(truth, rel=1e-3), name
    for spec in specs:
        assert fit_frozen(spec, artifact).R_sol == pytest.approx(
            spec.reference_ohm, rel=1e-3)


def test_wrong_pinned_inductance_moves_the_answer() -> None:
    """The positive control for the test above: pinning L must actually do something.

    Without this, ``test_pinned_inductance_is_consumed_not_fitted`` would pass just as
    happily if ``pinned_l_H`` were ignored entirely — SUBAGENT_RULES §3.1(e).
    """
    l_lead = 5e-4                            # far larger than any real lead
    truth = np.array([model_impedance(np.array([2.0e5]),
                                      {**TRUE_SHARED, "R0": 120.0, "R1": 680.0,
                                       "Qd": 2e-6},
                                      np.zeros(1, dtype=complex), L)[0]
                      for L in (0.0, l_lead)])
    assert abs(truth[1] - truth[0]) > 1.0


def test_l_is_not_a_bounded_parameter_anywhere() -> None:
    spec = synth("one", 10_000.0)
    assert spec.pinned_l_H == 0.0
    # It travels on the spectrum, not in the fit's box constraints.
    assert "pinned_l_H" in spec.__dataclass_fields__


# ── G_fixture, consumed point by point ───────────────────────────────────────

def _dielectric_table(n: int = 20) -> FixtureConductance:
    """``G = ωC·tanδ`` — this fixture's measured shape, ``d ln G/d ln f`` ≈ 1."""
    f = np.logspace(math.log10(14.28), math.log10(2.0e5), n)
    g = 2.0 * math.pi * f * 5.3e-11 * 0.05
    return FixtureConductance(freq_hz=tuple(f), G_S=tuple(g), exponent=1.0)


def test_fixture_admittance_is_evaluated_per_frequency_not_collapsed() -> None:
    table = _dielectric_table()
    freq = np.logspace(math.log10(20.0), math.log10(1.0e5), 25)
    shunt = fixture_admittance(freq, table, 0.0)
    assert isinstance(shunt, ShuntTable)
    assert shunt.y.shape == freq.shape
    # A scalar would give one value repeated. This spans three decades, monotonically,
    # because on this fixture the loss is dielectric.
    real = shunt.y.real
    assert np.all(np.diff(real) > 0)
    assert real[-1] / real[0] > 1e3


def test_fixture_admittance_adds_the_stray_capacitance_as_reactance() -> None:
    freq = np.array([100.0, 1000.0])
    shunt = fixture_admittance(freq, None, 5.3e-11)
    assert np.allclose(shunt.y.real, 0.0)
    assert shunt.y.imag == pytest.approx(2 * math.pi * freq * 5.3e-11)


def test_fixture_admittance_reports_points_beyond_the_measured_band() -> None:
    """Blocker 4. Holding the endpoint is a decision, so it is counted and logged."""
    table = _dielectric_table()
    freq = np.logspace(math.log10(1.2), math.log10(2.0e5), 40)   # starts below 14.28 Hz
    held = fixture_admittance(freq, table, 0.0, beyond_coverage="hold")
    assert held.n_held > 0
    assert held.coverage_hz[0] == pytest.approx(14.28, rel=1e-3)
    below = freq < held.coverage_hz[0]
    assert np.allclose(held.y.real[below], table.G_S[0])
    assert 0.0 < held.held_fraction < 1.0


def test_fixture_admittance_drop_policy_emits_nan_for_uncovered_points() -> None:
    table = _dielectric_table()
    freq = np.logspace(math.log10(1.2), math.log10(2.0e5), 40)
    dropped = fixture_admittance(freq, table, 0.0, beyond_coverage="drop")
    below = freq < dropped.coverage_hz[0]
    assert np.all(np.isnan(dropped.y.real[below]))
    assert np.all(np.isfinite(dropped.y.real[~below]))
    assert dropped.n_held == int(np.count_nonzero(below))


def test_fixture_admittance_rejects_an_unknown_policy() -> None:
    with pytest.raises(ValueError, match="beyond_coverage"):
        fixture_admittance(np.array([100.0]), _dielectric_table(), 0.0,
                           beyond_coverage="wing it")


def test_known_shunt_is_recovered_through_the_fit_not_absorbed() -> None:
    """A spectrum built *with* a fixture shunt is only recovered when it is supplied.

    The positive control that the shunt reaches the model: fitting the same spectrum
    with the shunt zeroed gives a materially different ``R_sol``.
    """
    table = _dielectric_table()
    specs, blind = [], []
    for label, r_sol in TRUE_R_SOL.items():
        freq = np.logspace(math.log10(14.28), math.log10(2.0e5), 40)
        y = fixture_admittance(freq, table, 5.3e-11).y
        params = {**TRUE_SHARED, "R0": 0.15 * r_sol, "R1": 0.85 * r_sol, "Qd": 2e-6}
        z = model_impedance(freq, params, y, 0.0)
        specs.append(ConstrainedSpectrum(label, freq, z, y, reference_ohm=r_sol))
        blind.append(ConstrainedSpectrum(label, freq, z, np.zeros(40, dtype=complex),
                                         reference_ohm=r_sol))

    supplied = fit_shared(specs)
    for spec in specs:
        assert fit_frozen(spec, supplied).R_sol == pytest.approx(
            spec.reference_ohm, rel=1e-3), spec.label

    ignored = fit_shared(blind)
    worst = max(abs(fit_frozen(s, ignored).R_sol / s.reference_ohm - 1.0)
                for s in blind)
    assert worst > 0.01, "zeroing the shunt changed nothing — it is not reaching the model"


# ── Admissibility: a refusal is a result ─────────────────────────────────────

def test_arc_is_resolved_detects_the_crossover_in_band() -> None:
    resolved = synth("wide", 70_000.0, band=(4.0, 2.0e5))
    assert arc_is_resolved(resolved.freq_hz, resolved.z)
    # Truncate away the low-frequency blocking tail and the crossover leaves the band.
    lo = synth("high_only", 70_000.0, band=(2.0e4, 2.0e5))
    assert not arc_is_resolved(lo.freq_hz, lo.z)


def test_arc_is_resolved_is_false_for_too_few_points() -> None:
    assert not arc_is_resolved(np.array([1.0, 2.0]), np.array([1 - 1j, 1 - 2j]))


def test_check_admissible_refuses_a_set_with_too_few_arc_resolved_spectra() -> None:
    good = synth("wide", 70_000.0, band=(4.0, 2.0e5))
    blind = [synth(f"high_only_{i}", r, band=(2.0e4, 2.0e5))
             for i, r in enumerate((38_000.0, 2_400.0))]
    verdict = check_admissible([good, *blind])
    assert isinstance(verdict, Admissibility)
    assert not verdict.admissible
    assert verdict.n_arc_resolved == 1
    assert verdict.arc_resolved == ("wide",)
    assert "resolve the geometric arc" in verdict.reason


def test_fit_shared_raises_rather_than_returning_a_bad_artifact() -> None:
    """Blocker 2. The refusal is the deliverable, not a degraded number."""
    good = synth("wide", 70_000.0, band=(4.0, 2.0e5))
    blind = [synth(f"high_only_{i}", r, band=(2.0e4, 2.0e5))
             for i, r in enumerate((38_000.0, 2_400.0))]
    with pytest.raises(InadmissibleFitSet, match="INADMISSIBLE"):
        fit_shared([good, *blind])


def test_check_admissible_refuses_a_single_spectrum() -> None:
    verdict = check_admissible([synth("only", 10_000.0)])
    assert not verdict.admissible
    assert "at least two spectra" in verdict.reason


def test_check_admissible_accepts_the_ladder(ladder) -> None:
    verdict = check_admissible(ladder)
    assert verdict.admissible
    assert verdict.n_arc_resolved >= 2
    assert verdict.n_residuals > verdict.n_free


def test_admissibility_travels_on_the_artifact(ladder) -> None:
    artifact = fit_shared(ladder)
    assert artifact.admissibility is not None
    assert artifact.admissibility.admissible


# ── Blocker 1: the tolerance is load-bearing ─────────────────────────────────

def test_constrained_fit_tol_is_far_tighter_than_the_scipy_default() -> None:
    assert CONSTRAINED_FIT_TOL <= 1e-12


def test_loose_tolerance_stops_short_of_the_minimum() -> None:
    """The stacked fit at scipy's default terminates *reporting success*.

    Measured on the real NIST set the gap is 8014 % against 1.56 %. Synthetically the
    gap is smaller — noise-free data is kind — so the assertion is on the cost the
    optimiser reached, which is the quantity that is actually wrong, and on the fact
    that the loose run still reports a successful status.
    """
    ladder = [synth(k, v) for k, v in TRUE_R_SOL.items()]
    loose = fit_shared(ladder, tol=1e-8)
    tight = fit_shared(ladder, tol=CONSTRAINED_FIT_TOL)
    assert tight.cost < loose.cost
    assert loose.status > 0, "the loose run reports success — that is the whole problem"
    assert tight.tol == CONSTRAINED_FIT_TOL and loose.tol == 1e-8


def test_loose_tolerance_is_warned_about(monkeypatch) -> None:
    """Asserted on the logger call, not on log capture — structlog routing varies."""
    from softae.analysis.eis import constrained_fit as module

    events: list[tuple[str, dict]] = []
    monkeypatch.setattr(
        module.logger, "warning",
        lambda event, **kw: events.append((event, kw)))
    fit_shared([synth(k, v) for k, v in TRUE_R_SOL.items()], tol=1e-6)
    assert [e for e, _ in events] == ["eis_constrained_fit_loose_tolerance"]
    assert events[0][1]["tol"] == 1e-6


def test_tight_tolerance_is_not_warned_about(monkeypatch) -> None:
    """The negative half. Without it the test above cannot distinguish a warning that
    fires on the loose case from one that fires unconditionally."""
    from softae.analysis.eis import constrained_fit as module

    events: list[str] = []
    monkeypatch.setattr(module.logger, "warning",
                        lambda event, **kw: events.append(event))
    fit_shared([synth(k, v) for k, v in TRUE_R_SOL.items()])
    assert events == []


def test_tolerance_reaches_the_optimiser(monkeypatch) -> None:
    """Positive control: the keyword must actually arrive at ``least_squares``.

    Without this the test above could pass on two runs that both used the default —
    SUBAGENT_RULES §3.1(e).
    """
    from softae.analysis.eis import constrained_fit as module

    seen: list[float] = []
    real = module.least_squares

    def spy(*args, **kwargs):
        seen.append(kwargs.get("ftol"))
        return real(*args, **kwargs)

    monkeypatch.setattr(module, "least_squares", spy)
    fit_shared([synth(k, v) for k, v in TRUE_R_SOL.items()], tol=1e-9)
    assert seen and set(seen) == {1e-9}


# ── Blocker 3: multi-start ───────────────────────────────────────────────────

def test_multistart_grid_spans_decades_either_side_of_the_estimate() -> None:
    assert min(R_SOL_SEED_MULTIPLIERS) <= 0.1
    assert max(R_SOL_SEED_MULTIPLIERS) >= 100.0
    assert 1.0 in R_SOL_SEED_MULTIPLIERS


def test_fit_frozen_reports_its_seed_spread(ladder) -> None:
    """A good artifact is seed-insensitive, and the spread is how that is known."""
    artifact = fit_shared(ladder)
    fit = fit_frozen(ladder[0], artifact)
    assert fit.seed_spread_pct == pytest.approx(0.0, abs=1e-6)
    assert fit.seed_multiplier in R_SOL_SEED_MULTIPLIERS


def test_fit_frozen_recovers_from_a_deliberately_bad_single_seed(ladder) -> None:
    artifact = fit_shared(ladder)
    spec = ladder[0]
    only_bad = fit_frozen(spec, artifact, multipliers=(0.001,))
    every = fit_frozen(spec, artifact, multipliers=R_SOL_SEED_MULTIPLIERS)
    assert every.cost <= only_bad.cost
    assert every.R_sol == pytest.approx(spec.reference_ohm, rel=1e-3)


# ── Validation surface ───────────────────────────────────────────────────────

def test_holdout_result_error_is_signed_relative_percent() -> None:
    assert HoldoutResult("x", 100.0, 110.0).error_pct == pytest.approx(10.0)
    assert HoldoutResult("x", 100.0, 90.0).error_pct == pytest.approx(-10.0)
    assert math.isnan(HoldoutResult("x", 0.0, 1.0).error_pct)


def test_holdout_report_in_sample_scores_every_reference(ladder) -> None:
    report = holdout_report(ladder, kind="in_sample")
    assert report.kind == "in_sample"
    assert len(report.results) == len(ladder)
    assert report.mean_abs_error_pct < 1.0
    assert report.refused == ()


def test_holdout_report_leave_one_out_scores_only_held_out_spectra(ladder) -> None:
    report = holdout_report(ladder, kind="leave_one_out")
    assert report.kind == "leave_one_out"
    assert len(report.results) + len(report.refused) == len(ladder)
    assert report.worst_abs_error_pct >= report.mean_abs_error_pct


def test_holdout_report_records_refused_folds_rather_than_skipping_them() -> None:
    """A fold dropped for inadmissibility must be visible, not averaged away."""
    good = [synth("wide_a", 70_000.0), synth("wide_b", 38_000.0)]
    blind = synth("high_only", 2_400.0, band=(2.0e4, 2.0e5))
    report = holdout_report([*good, blind], kind="leave_one_out")
    refused = {label for label, _ in report.refused}
    assert refused == {"wide_a", "wide_b"}
    assert "INADMISSIBLE" in dict(report.refused)["wide_a"]
    assert "refused" in report.describe()


def test_holdout_report_rejects_an_unknown_kind(ladder) -> None:
    with pytest.raises(ValueError, match="unknown holdout kind"):
        holdout_report(ladder, kind="optimistic")


# ── Housekeeping ─────────────────────────────────────────────────────────────

def test_constrained_spectrum_rejects_mismatched_array_lengths() -> None:
    with pytest.raises(ValueError, match="points against"):
        ConstrainedSpectrum("bad", np.arange(5.0), np.zeros(4, dtype=complex),
                            np.zeros(5, dtype=complex))


def test_conductance_r_sol_reads_a_pure_resistor() -> None:
    z = np.full(10, 4700.0 + 0j)
    assert conductance_r_sol(np.logspace(1, 5, 10), z) == pytest.approx(4700.0)


def test_artifact_railed_names_a_parameter_resting_on_a_bound() -> None:
    from softae.analysis.eis.constrained_fit import SharedArtifact

    assert SharedArtifact(Qg=1e-9, ng=0.9, nd=0.8).railed() == ()
    assert SharedArtifact(Qg=1e-9, ng=0.9, nd=BOUNDS["nd"][1]).railed() == ("nd",)


def test_module_is_not_wired_into_any_live_path() -> None:
    """It ships inert. This test is what makes that a contract rather than a comment."""
    src = Path(__file__).resolve().parents[1] / "src" / "softae"
    importers = [p for p in src.rglob("*.py")
                 if p.name != "constrained_fit.py"
                 and "constrained_fit" in p.read_text(encoding="utf-8")]
    assert importers == [], f"constrained_fit is referenced by {importers}"


# ── Answer keys. Real data; skipped when it is not here ──────────────────────

AMP_KCL = Path(r"C:\Users\Osuji\AppData\Local\Programs\Python\Python311\Scripts"
               r"\AMP_v1\data\calibration\2026_0616")
#: R_sol from AMP_v1's own constrained artifact, which scores 1.15 % against NIST.
AMP_R_SOL = {"kcl_45uS": 71007.64, "kcl_84uS": 37933.07,
             "kcl_1413uS": 2347.67, "kcl_4500uS": 775.56}


def _truncate_hf_inductive(f: np.ndarray, z: np.ndarray) -> np.ndarray:
    """``gate_hf_inductive``'s rule, applied here: drop the contiguous ``Im Z > 0`` run.

    **This is the one preparation step the constrained fit cannot do without**, measured
    on the four NIST standards: with it the in-sample ``R_sol`` error is 2.9 %, without
    it 6295 %. The short-blank correction, the |Z| window and the linear-KK truncation
    each move the number by little or nothing on this set. A blocking cell has no
    inductance of its own, so an ``Im Z > 0`` point at the top of the band is the
    fixture's lead — and left in, the optimiser absorbs it into ``Qg``, which is a
    shared parameter, so a handful of points at one end of one spectrum corrupts the
    artifact for the whole set.

    The rule lives in :func:`~softae.analysis.eis.gates.gate_hf_inductive` and already
    ships in the gated engine; it is restated here rather than imported so this test
    exercises the fit rather than the gate's signature.
    """
    keep = np.ones(f.size, dtype=bool)
    for i in np.argsort(f)[::-1]:
        if z.imag[i] > 0:
            keep[i] = False
        else:
            break
    return keep


def _load_amp_csv(path: Path) -> tuple[np.ndarray, np.ndarray]:
    freq, real, neg_imag = [], [], []
    for line in path.read_text().splitlines():
        s = line.strip()
        if not s or s.startswith("#") or s.startswith("frequency"):
            continue
        a, b, c = s.split(",")[:3]
        freq.append(float(a))
        real.append(float(b))
        neg_imag.append(float(c))
    f = np.asarray(freq)
    z = np.asarray(real) - 1j * np.asarray(neg_imag)
    order = np.argsort(f)
    return f[order], z[order]


@pytest.mark.skipif(not AMP_KCL.is_dir(), reason="AMP_v1 NIST standards not present")
def test_answer_key_nist_standards_split_admissible_from_inadmissible_folds() -> None:
    """The gate must fire on exactly the folds that produce a wrong artifact.

    Measured with the gate bypassed: dropping ``kcl_45uS`` or ``kcl_84uS`` gives
    ``R_sol`` −84.1 % / −74.4 % on the held-out standard, while dropping either
    concentrated standard gives +2.5 % / +1.8 %. This asserts the gate's verdict
    matches that partition — the §3.2 check that the branch is reached by real data.
    """
    specs = []
    for label, ref in AMP_R_SOL.items():
        f, z = _load_amp_csv(AMP_KCL / f"{label}.csv")
        keep = np.isfinite(z) & (z.real > 0)
        specs.append(ConstrainedSpectrum(label, f[keep], z[keep],
                                         np.zeros(int(keep.sum()), dtype=complex),
                                         reference_ohm=ref))

    verdict = {s.label: arc_is_resolved(s.freq_hz, s.z) for s in specs}
    assert verdict == {"kcl_45uS": True, "kcl_84uS": True,
                       "kcl_1413uS": False, "kcl_4500uS": False}

    refused = {label for label, _ in
               holdout_report(specs, kind="leave_one_out").refused}
    assert refused == {"kcl_45uS", "kcl_84uS"}


@pytest.mark.skipif(not AMP_KCL.is_dir(), reason="AMP_v1 NIST standards not present")
def test_answer_key_nist_standards_reproduce_the_constrained_r_sol() -> None:
    """In-sample ``R_sol`` against AMP_v1's constrained artifact: 2.9 % mean here.

    The preparation is deliberately thinner than the offline harness's (no short-blank
    correction, no |Z| window, no linear-KK truncation, ``L`` pinned to 0) because those
    steps were measured to be worth ~1.3 percentage points between them, while
    :func:`_truncate_hf_inductive` is worth three orders of magnitude. So the tolerance
    is loose on purpose: the claim under test is that the constrained fit lands *near*
    an independent codebase's answer on a quantity where an unconstrained fit of the
    same circuit is off by orders of magnitude — not that it reproduces a decimal.
    """
    specs = []
    for label, ref in AMP_R_SOL.items():
        f, z = _load_amp_csv(AMP_KCL / f"{label}.csv")
        keep = np.isfinite(z) & (z.real > 0) & _truncate_hf_inductive(f, z)
        specs.append(ConstrainedSpectrum(label, f[keep], z[keep],
                                         np.zeros(int(keep.sum()), dtype=complex),
                                         reference_ohm=ref))
    report = holdout_report(specs, kind="in_sample")
    assert report.mean_abs_error_pct < 10.0, report.describe()
    assert report.worst_abs_error_pct < 15.0, report.describe()
